language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0"
  - rbx-2.1.1
  - rbx-2.2.0
  - rbx-2.2.1
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
allow_failures:
  rvm:
    - ruby-head
    - rbx-2.2.0
    - rbx-2.2.1